INFO | boot | api_search | 2018-10-17 10:09:52 | 127.0.0.1 | game=Rocket%20League
INFO | boot | api_search | 2018-10-17 10:09:58 | 127.0.0.1 | name=Rocket%20League
ERROR | app | log_exception | Exception on /genres/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\AlexM\Documents\Uni\Y3\AWT\mcgill_alex_set09103_cw1\server\boot.py", line 180, in genre
    genres = get_genre_info()
  File "C:\Users\AlexM\Documents\Uni\Y3\AWT\mcgill_alex_set09103_cw1\server\boot.py", line 228, in get_genre_info
    for genre in game[str(appid)]["data"]["genres"]:
KeyError: 'genres'
ERROR | app | log_exception | Exception on /genres/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\AlexM\Documents\Uni\Y3\AWT\mcgill_alex_set09103_cw1\server\boot.py", line 180, in genre
    genres = get_genre_info()
  File "C:\Users\AlexM\Documents\Uni\Y3\AWT\mcgill_alex_set09103_cw1\server\boot.py", line 228, in get_genre_info
    for genre in game[str(appid)]["data"]["genres"].iteritems():
AttributeError: 'list' object has no attribute 'iteritems'
ERROR | app | log_exception | Exception on /genres/ [GET]
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Python27\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Python27\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\AlexM\Documents\Uni\Y3\AWT\mcgill_alex_set09103_cw1\server\boot.py", line 180, in genre
    genres = get_genre_info()
  File "C:\Users\AlexM\Documents\Uni\Y3\AWT\mcgill_alex_set09103_cw1\server\boot.py", line 228, in get_genre_info
    for genre in game[str(appid)]["data"]["genres"].values():
AttributeError: 'list' object has no attribute 'values'
